name = "truehhart-com"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = true

[assets]
directory = "public"

[[rules]]
type = "Text"
globs = ["**/*.toml"]
fallthrough = true

[[routes]]
pattern = "truehhart.com"
custom_domain = true
