name = "truehhart-com"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = true

[[rules]]
type = "Text"
globs = ["**/*.toml"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.svg"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[[routes]]
pattern = "truehhart.com"
custom_domain = true
