[[degrees]]
degree = "Master of Science in Strategic Innovation Management"
institution = "ITMO University"
year = "2020"

[[degrees]]
degree = "Bachelor of Science in Business Informatics"
institution = "Peter the Great St. Petersburg Polytechnic University"
year = "2018"
